#!/bin/sh
#
# vi:set et ai sw=2 sts=2 ts=2: */

test "x$DISPLAY" != "x" || DISPLAY=:0

if [ "x$1" = "x--desktop" ]; then
  method="DisplayDesktopDialog"
else
  method="DisplayPreferencesDialog"
fi

output=`dbus-send --session --print-reply --dest=org.xfce.FileManager \
  /org/xfce/FileManager org.xfce.FileManager.$method \
  "string:$DISPLAY" "string:$DESKTOP_STARTUP_ID"`

if ! [ $? -eq 0 ]; then
  echo $output
  exit 1
fi
